---
- hosts: jenkins
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Ensure that software packages are up to date
      yum:
        name: '*'
    
    - name: Add the Jenkins repo and key
      become: true
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Ensure that software packages are up to date and remove obsolete packages
      yum:
        name: '*'
        state: latest

    - name: Install Java
      become: true
      command: amazon-linux-extras install java-openjdk11 -y
    
    - name: Install Jenkins
      become: true
      yum:
        name: jenkins
        state: latest

    - name: Start jenkins and enable the Jenkins service to start at boot
      become: true
      systemd:
        name: jenkins
        state: started
        enabled: yes

