---
- hosts: knodes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Ensure that software packages are up to date
      yum:
        name: '*'

    - name: Install Docker
      become: true
      yum:
        name: docker
        state: latest
    
    - name: Check docker is active
      become: true
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Ensure group "docker" exists
      become: true
      group:
        name: docker
        state: present

          #- name: Add the user to docker group create that group
          #become: true
          #command: usermod -aG docker ec2-user && inewgrp docker

    - name: Adding ec2-user to docker group
      become: true
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Reset connection for this new group to be reflected
      meta: reset_connection

