---
- hosts: knodes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Ensure that software packages are up to date
      yum:
        name: '*'

    - name: Install Docker
      become: true
      yum:
        name: docker
        state: latest
    
    - name: Check docker is active
      become: true
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present

    - name:  Add the user to docker group create that group
      command: usermod -aG docker ec2-user
    
    # - name: Adding ec2-user to docker group
    #   become: true
    #   become_method: sudo
    #   user:
    #     name: $USER
    #     groups: docker
    #     append: yes
