---
- hosts: knodes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Ensure that software packages are up to date
      yum:
        name: '*'

    - name: Install Docker
      become: true
      yum:
        name: docker
        state: latest
    
    - name: Check docker is active
      become: true
      service:
        name: docker
        state: started
        enabled: yes
    
    # - name: Ensure group "docker" exists
    #   become: true
    #   group:
    #     name: docker
    #     state: present

    - name:  Add the user to docker group create that group
      become_method: sudo
      command: usermod -aG docker $USER && newgrp docker
    
    # - name: Adding ec2-user to docker group
    #   become: true
    #   become_method: sudo
    #   user:
    #     name: $USER
    #     groups: docker
    #     append: yes
